# Generated by Django 4.0.5 on 2022-06-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_site_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='technlogies',
            new_name='technologies',
        ),
    ]
