# Generated by Django 4.0.5 on 2022-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_technlogies_site_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.CharField(max_length=2),
        ),
    ]
