# Generated by Django 4.0.5 on 2022-06-13 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_alter_rating_content_alter_rating_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='usability',
        ),
        migrations.CreateModel(
            name='RatingUsability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usability', models.CharField(blank=True, max_length=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site')),
            ],
        ),
        migrations.CreateModel(
            name='RatingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site')),
            ],
        ),
    ]
