# Generated by Django 4.0.5 on 2022-06-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_rating_content_remove_rating_usability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratingcontent',
            name='content',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratingusability',
            name='usability',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
